"""initial

Revision ID: 0b223aad73a2
Revises:
Create Date: 2023-04-01 11:14:06.117031

"""
import sqlalchemy as sa
import sqlmodel  # NEW

from alembic import op

# import geoalchemy2          # POSTGIS


# revision identifiers, used by Alembic.
revision = "0b223aad73a2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "energy",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "energy_type",
            sa.Enum(
                "CONSUMO_ADMINISTRATIVO",
                "CONSUMO_LOGISTICO",
                "CONSUMO_DE_DISTIBUCION",
                name="energytype",
            ),
            nullable=True,
        ),
        sa.Column(
            "emission_type",
            sa.Enum(
                "EMISIONES_DIRECTAS",
                "EMISIONES_INDIRECTAS",
                "OTRAS_EMISIONES_INDIRECTAS",
                name="emissiontype",
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fuel",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "fuel_type",
            sa.Enum(
                "COMBUSTIBLE_ADMINISTRATIVO",
                "COMBUSTIBLE_INDIRECTO_DE_PROVEEDOR",
                "COMBUSTIBLE_DE_LOGISTICA",
                name="fueltype",
            ),
            nullable=True,
        ),
        sa.Column(
            "emission_type",
            sa.Enum(
                "EMISIONES_DIRECTAS",
                "EMISIONES_INDIRECTAS",
                "OTRAS_EMISIONES_INDIRECTAS",
                name="emissiontype",
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "oil",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "oil_type",
            sa.Enum(
                "CONSUMO_ADMINISTRATIVO",
                "CONSUMO_LOGISTICO",
                "CONSUMO_DE_OPERACION",
                name="oiltype",
            ),
            nullable=True,
        ),
        sa.Column(
            "emission_type",
            sa.Enum(
                "EMISIONES_DIRECTAS",
                "EMISIONES_INDIRECTAS",
                "OTRAS_EMISIONES_INDIRECTAS",
                name="emissiontype",
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roadtrip",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "emission_type",
            sa.Enum(
                "EMISIONES_DIRECTAS",
                "EMISIONES_INDIRECTAS",
                "OTRAS_EMISIONES_INDIRECTAS",
                name="emissiontype",
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("roadtrip")
    op.drop_table("oil")
    op.drop_table("fuel")
    op.drop_table("energy")
    # ### end Alembic commands ###
